name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release-linux-amd64:
    name: Linux amd64
    runs-on: ubuntu-latest

    env:
      GOOS: linux
      GOARCH: amd64

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Install deps (amd64)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc \
            pkg-config \
            libx11-dev \
            libxfixes-dev

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-linux-arm64:
    name: Linux arm64
    runs-on: ubuntu-latest
    needs: release-linux-amd64

    env:
      GOOS: linux
      GOARCH: arm64
      CGO_ENABLED: 1
      CC: aarch64-linux-gnu-gcc

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Install deps (arm64 cross)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-aarch64-linux-gnu \
            pkg-config \
            libx11-dev:arm64 \
            libxfixes-dev:arm64

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-macos:
    name: macOS
    runs-on: macos-latest
    needs: release-linux-arm64

    env:
      GOOS: darwin

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Install deps
        run: brew install pkg-config

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
